[2024-06-09T23:02:16.010+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:02:16.015+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:02:16.020+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:02:16.020+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:02:17.534+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:02:17.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:02:17.538+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:02:17.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 1.562 seconds
[2024-06-09T23:02:47.704+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:02:47.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:02:47.708+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:02:47.707+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:02:48.159+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:02:48.144+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:02:48.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:02:48.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.483 seconds
[2024-06-09T23:03:18.287+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:03:18.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:03:18.292+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:03:18.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:03:18.729+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:03:18.713+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:03:18.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:03:18.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.463 seconds
[2024-06-09T23:03:48.881+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:03:48.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:03:48.887+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:03:48.886+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:03:49.368+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:03:49.350+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:03:49.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:03:49.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.511 seconds
[2024-06-09T23:04:19.534+0000] {processor.py:161} INFO - Started process (PID=287) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:04:19.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:04:19.538+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:04:19.538+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:04:19.958+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:04:19.938+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:04:19.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:04:19.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.452 seconds
[2024-06-09T23:04:50.957+0000] {processor.py:161} INFO - Started process (PID=347) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:04:50.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:04:50.960+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:04:50.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:04:51.415+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:04:51.384+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:04:51.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:04:51.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.487 seconds
[2024-06-09T23:05:21.817+0000] {processor.py:161} INFO - Started process (PID=411) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:05:21.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:05:21.821+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:05:21.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:05:22.287+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:05:22.256+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:05:22.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:05:22.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.496 seconds
[2024-06-09T23:05:52.965+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:05:52.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:05:52.969+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:05:52.969+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:05:53.450+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:05:53.423+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:05:53.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:05:53.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.517 seconds
[2024-06-09T23:06:24.352+0000] {processor.py:161} INFO - Started process (PID=532) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:06:24.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:06:24.356+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:06:24.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:06:24.810+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:06:24.784+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:06:24.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:06:24.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.480 seconds
[2024-06-09T23:06:55.005+0000] {processor.py:161} INFO - Started process (PID=592) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:06:55.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:06:55.010+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:06:55.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:06:55.453+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:06:55.440+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:06:55.457+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:06:55.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.471 seconds
[2024-06-09T23:07:25.693+0000] {processor.py:161} INFO - Started process (PID=652) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:07:25.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:07:25.699+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:07:25.699+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:07:26.111+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:07:26.099+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:07:26.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:07:26.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.441 seconds
[2024-06-09T23:07:56.447+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:07:56.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:07:56.452+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:07:56.452+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:07:56.974+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:07:56.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:07:56.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:07:56.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.551 seconds
[2024-06-09T23:08:27.138+0000] {processor.py:161} INFO - Started process (PID=774) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:08:27.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:08:27.142+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:08:27.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:08:27.588+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:08:27.578+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:08:27.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:08:27.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.474 seconds
[2024-06-09T23:08:57.801+0000] {processor.py:161} INFO - Started process (PID=836) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:08:57.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:08:57.806+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:08:57.805+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:08:58.267+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:08:58.243+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:08:58.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:08:58.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.496 seconds
[2024-06-09T23:09:28.995+0000] {processor.py:161} INFO - Started process (PID=897) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:09:28.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:09:29.000+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:09:29.000+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:09:29.442+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:09:29.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:09:29.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:09:29.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.469 seconds
[2024-06-09T23:09:59.542+0000] {processor.py:161} INFO - Started process (PID=959) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:09:59.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:09:59.548+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:09:59.547+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:10:00.010+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:09:59.995+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:10:00.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:10:00.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.489 seconds
[2024-06-09T23:10:30.230+0000] {processor.py:161} INFO - Started process (PID=1016) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:10:30.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:10:30.233+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:10:30.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:10:30.650+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:10:30.629+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:10:30.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:10:30.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.446 seconds
[2024-06-09T23:11:00.916+0000] {processor.py:161} INFO - Started process (PID=1076) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:11:00.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:11:00.920+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:11:00.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:11:01.366+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:11:01.354+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:11:01.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:11:01.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.475 seconds
[2024-06-09T23:11:31.759+0000] {processor.py:161} INFO - Started process (PID=1137) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:11:31.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:11:31.763+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:11:31.762+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:11:32.170+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:11:32.159+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:11:32.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:11:32.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.458 seconds
[2024-06-09T23:12:02.328+0000] {processor.py:161} INFO - Started process (PID=1201) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:12:02.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:12:02.331+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:12:02.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:12:02.740+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:12:02.717+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:12:02.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:12:02.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.441 seconds
[2024-06-09T23:12:32.881+0000] {processor.py:161} INFO - Started process (PID=1269) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:12:32.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:12:32.885+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:12:32.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:12:33.340+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:12:33.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:12:33.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:12:33.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.483 seconds
[2024-06-09T23:13:03.799+0000] {processor.py:161} INFO - Started process (PID=1332) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:13:03.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:13:03.804+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:13:03.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:13:04.242+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:13:04.213+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:13:04.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:13:04.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.467 seconds
[2024-06-09T23:13:34.356+0000] {processor.py:161} INFO - Started process (PID=1393) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:13:34.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:13:34.360+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:13:34.360+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:13:34.662+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:13:34.642+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:13:34.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:13:34.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.331 seconds
[2024-06-09T23:14:04.857+0000] {processor.py:161} INFO - Started process (PID=1453) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:14:04.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:14:04.860+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:14:04.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:14:05.149+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:14:05.134+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:14:05.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:14:05.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.320 seconds
[2024-06-09T23:14:35.310+0000] {processor.py:161} INFO - Started process (PID=1513) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:14:35.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:14:35.314+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:14:35.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:14:35.654+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:14:35.634+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:14:35.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:14:35.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.373 seconds
[2024-06-09T23:15:06.622+0000] {processor.py:161} INFO - Started process (PID=1573) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:15:06.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:15:06.627+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:15:06.627+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:15:06.975+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:15:06.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:15:06.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:15:07.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.430 seconds
[2024-06-09T23:15:37.239+0000] {processor.py:161} INFO - Started process (PID=1636) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:15:37.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:15:37.244+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:15:37.243+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:15:37.576+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:15:37.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:15:37.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:15:37.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.368 seconds
[2024-06-09T23:16:07.799+0000] {processor.py:161} INFO - Started process (PID=1698) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:16:07.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:16:07.804+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:16:07.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:16:08.129+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:16:08.117+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:16:08.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:16:08.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.359 seconds
[2024-06-09T23:16:38.310+0000] {processor.py:161} INFO - Started process (PID=1760) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:16:38.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:16:38.315+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:16:38.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:16:38.658+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:16:38.646+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:16:38.663+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:16:38.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.375 seconds
[2024-06-09T23:17:09.193+0000] {processor.py:161} INFO - Started process (PID=1822) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:17:09.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:17:09.198+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:17:09.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:17:09.527+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:17:09.495+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:17:09.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:17:09.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.362 seconds
[2024-06-09T23:17:39.687+0000] {processor.py:161} INFO - Started process (PID=1883) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:17:39.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:17:39.693+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:17:39.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:17:40.054+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:17:40.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:17:40.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:17:40.081+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.400 seconds
[2024-06-09T23:18:11.038+0000] {processor.py:161} INFO - Started process (PID=1943) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:18:11.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:18:11.044+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:18:11.044+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:18:11.383+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:18:11.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:18:11.391+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:18:11.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.374 seconds
[2024-06-09T23:18:41.683+0000] {processor.py:161} INFO - Started process (PID=2003) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:18:41.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:18:41.688+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:18:41.688+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:18:42.029+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:18:42.000+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:18:42.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:18:42.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.373 seconds
[2024-06-09T23:19:12.491+0000] {processor.py:161} INFO - Started process (PID=2063) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:19:12.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:19:12.495+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:19:12.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:19:12.796+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:19:12.780+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:19:12.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:19:12.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.333 seconds
[2024-06-09T23:19:42.977+0000] {processor.py:161} INFO - Started process (PID=2123) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:19:42.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:19:42.982+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:19:42.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:19:43.326+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:19:43.304+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:19:43.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:19:43.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.382 seconds
[2024-06-09T23:20:13.715+0000] {processor.py:161} INFO - Started process (PID=2183) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:20:13.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:20:13.721+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:20:13.720+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:20:14.065+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:20:14.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:20:14.072+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:20:14.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.379 seconds
[2024-06-09T23:20:44.646+0000] {processor.py:161} INFO - Started process (PID=2243) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:20:44.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:20:44.649+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:20:44.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:20:44.962+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:20:44.950+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:20:44.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:20:44.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.342 seconds
[2024-06-09T23:21:15.098+0000] {processor.py:161} INFO - Started process (PID=2303) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:21:15.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:21:15.103+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:21:15.103+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:21:15.418+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:21:15.395+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:21:15.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:21:15.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.347 seconds
[2024-06-09T23:21:45.650+0000] {processor.py:161} INFO - Started process (PID=2363) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:21:45.652+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:21:45.654+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:21:45.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:21:45.995+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:21:45.977+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:21:45.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:21:46.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.373 seconds
[2024-06-09T23:22:16.195+0000] {processor.py:161} INFO - Started process (PID=2423) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:22:16.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:22:16.200+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:22:16.200+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:22:16.512+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:22:16.498+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:22:16.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:22:16.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.346 seconds
[2024-06-09T23:22:46.765+0000] {processor.py:161} INFO - Started process (PID=2482) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:22:46.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:22:46.769+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:22:46.769+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:22:47.097+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:22:47.078+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:22:47.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:22:47.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.358 seconds
[2024-06-09T23:23:17.306+0000] {processor.py:161} INFO - Started process (PID=2542) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:23:17.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:23:17.309+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:23:17.309+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:23:17.643+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:23:17.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:23:17.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:23:17.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.367 seconds
[2024-06-09T23:23:47.970+0000] {processor.py:161} INFO - Started process (PID=2602) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:23:47.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:23:47.974+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:23:47.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:23:48.282+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:23:48.267+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:23:48.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:23:48.301+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.337 seconds
[2024-06-09T23:24:18.608+0000] {processor.py:161} INFO - Started process (PID=2662) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:24:18.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:24:18.612+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:24:18.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:24:18.952+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:24:18.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:24:18.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:24:18.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.375 seconds
[2024-06-09T23:24:49.207+0000] {processor.py:161} INFO - Started process (PID=2721) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:24:49.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:24:49.211+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:24:49.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:24:49.550+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:24:49.536+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:24:49.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:24:49.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.371 seconds
[2024-06-09T23:25:19.882+0000] {processor.py:161} INFO - Started process (PID=2781) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:25:19.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:25:19.886+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:25:19.886+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:25:20.216+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:25:20.201+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:25:20.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:25:20.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.362 seconds
[2024-06-09T23:25:50.465+0000] {processor.py:161} INFO - Started process (PID=2841) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:25:50.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:25:50.468+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:25:50.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:25:50.771+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:25:50.752+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:25:50.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:25:50.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.335 seconds
[2024-06-09T23:26:21.048+0000] {processor.py:161} INFO - Started process (PID=2901) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:26:21.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:26:21.051+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:26:21.051+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:26:21.370+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:26:21.346+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:26:21.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:26:21.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.350 seconds
[2024-06-09T23:26:51.715+0000] {processor.py:161} INFO - Started process (PID=2961) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:26:51.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:26:51.719+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:26:51.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:26:52.031+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:26:52.016+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:26:52.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:26:52.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.343 seconds
[2024-06-09T23:27:22.268+0000] {processor.py:161} INFO - Started process (PID=3022) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:27:22.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:27:22.272+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:27:22.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:27:22.606+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:27:22.584+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:27:22.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:27:22.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.369 seconds
[2024-06-09T23:27:53.060+0000] {processor.py:161} INFO - Started process (PID=3082) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:27:53.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:27:53.063+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:27:53.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:27:53.369+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:27:53.354+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:27:53.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:27:53.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.334 seconds
[2024-06-09T23:28:23.873+0000] {processor.py:161} INFO - Started process (PID=3142) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:28:23.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:28:23.879+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:28:23.878+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:28:24.219+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:28:24.204+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:28:24.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:28:24.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.372 seconds
[2024-06-09T23:28:54.430+0000] {processor.py:161} INFO - Started process (PID=3202) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:28:54.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:28:54.434+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:28:54.433+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:28:54.742+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:28:54.723+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:28:54.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:28:54.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.339 seconds
[2024-06-09T23:29:24.962+0000] {processor.py:161} INFO - Started process (PID=3262) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:29:24.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:29:24.965+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:29:24.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:29:25.297+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:29:25.282+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:29:25.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:29:25.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.366 seconds
[2024-06-09T23:29:55.420+0000] {processor.py:161} INFO - Started process (PID=3322) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:29:55.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:29:55.426+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:29:55.425+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:29:55.756+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:29:55.745+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:29:55.760+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:29:55.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.363 seconds
[2024-06-09T23:30:25.949+0000] {processor.py:161} INFO - Started process (PID=3384) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:30:25.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:30:25.954+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:30:25.954+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:30:26.275+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:30:26.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:30:26.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:30:26.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.352 seconds
[2024-06-09T23:30:56.688+0000] {processor.py:161} INFO - Started process (PID=3442) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:30:56.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:30:56.692+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:30:56.692+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:30:57.014+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:30:56.989+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:30:57.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:30:57.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.357 seconds
[2024-06-09T23:31:27.383+0000] {processor.py:161} INFO - Started process (PID=3502) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:31:27.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:31:27.387+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:31:27.387+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:31:27.744+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:31:27.721+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:31:27.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:31:27.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.386 seconds
[2024-06-09T23:31:57.912+0000] {processor.py:161} INFO - Started process (PID=3562) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:31:57.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:31:57.916+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:31:57.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:31:58.227+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:31:58.214+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:31:58.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:31:58.246+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.339 seconds
[2024-06-09T23:32:28.799+0000] {processor.py:161} INFO - Started process (PID=3622) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:32:28.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:32:28.802+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:32:28.802+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:32:29.112+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:32:29.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:32:29.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:32:29.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.339 seconds
[2024-06-09T23:32:59.535+0000] {processor.py:161} INFO - Started process (PID=3682) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:32:59.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:32:59.539+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:32:59.539+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:32:59.999+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:32:59.989+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:33:00.006+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:33:00.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.494 seconds
[2024-06-09T23:33:30.475+0000] {processor.py:161} INFO - Started process (PID=3746) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:33:30.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:33:30.479+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:33:30.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:33:30.890+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:33:30.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:33:30.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:33:30.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.441 seconds
[2024-06-09T23:34:01.118+0000] {processor.py:161} INFO - Started process (PID=3809) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:34:01.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:34:01.122+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:34:01.122+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:34:01.471+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:34:01.449+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:34:01.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:34:01.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.387 seconds
[2024-06-09T23:34:31.637+0000] {processor.py:161} INFO - Started process (PID=3872) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:34:31.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:34:31.641+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:34:31.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:34:31.954+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:34:31.938+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:34:31.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:34:31.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.347 seconds
[2024-06-09T23:35:03.038+0000] {processor.py:161} INFO - Started process (PID=3932) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:35:03.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:35:03.042+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:35:03.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:35:03.459+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:35:03.446+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:35:03.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:35:03.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.445 seconds
[2024-06-09T23:35:33.557+0000] {processor.py:161} INFO - Started process (PID=3994) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:35:33.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:35:33.560+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:35:33.560+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:35:33.980+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:35:33.955+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:35:33.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:35:34.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.451 seconds
[2024-06-09T23:36:04.872+0000] {processor.py:161} INFO - Started process (PID=4054) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:36:04.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:36:04.876+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:36:04.876+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:36:05.311+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:36:05.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:36:05.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:36:05.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.463 seconds
[2024-06-09T23:36:35.437+0000] {processor.py:161} INFO - Started process (PID=4119) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:36:35.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:36:35.443+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:36:35.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:36:35.886+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:36:35.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:36:35.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:36:35.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.478 seconds
[2024-06-09T23:37:06.565+0000] {processor.py:161} INFO - Started process (PID=4179) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:37:06.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:37:06.570+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:37:06.570+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:37:07.067+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:37:07.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:37:07.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:37:07.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.529 seconds
[2024-06-09T23:37:38.061+0000] {processor.py:161} INFO - Started process (PID=4245) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:37:38.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:37:38.065+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:37:38.065+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:37:38.469+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:37:38.448+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:37:38.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:37:38.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.436 seconds
[2024-06-09T23:38:09.048+0000] {processor.py:161} INFO - Started process (PID=4305) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:38:09.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:38:09.053+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:38:09.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:38:09.496+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:38:09.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:38:09.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:38:09.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.481 seconds
[2024-06-09T23:38:40.476+0000] {processor.py:161} INFO - Started process (PID=4365) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:38:40.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:38:40.479+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:38:40.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:38:40.878+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:38:40.853+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:38:40.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:38:40.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.437 seconds
[2024-06-09T23:39:11.723+0000] {processor.py:161} INFO - Started process (PID=4425) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:39:11.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:39:11.727+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:39:11.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:39:12.161+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:39:12.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:39:12.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:39:12.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.461 seconds
[2024-06-09T23:39:43.077+0000] {processor.py:161} INFO - Started process (PID=4485) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:39:43.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:39:43.081+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:39:43.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:39:43.490+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:39:43.464+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:39:43.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:39:43.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.440 seconds
[2024-06-09T23:40:14.570+0000] {processor.py:161} INFO - Started process (PID=4545) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:40:14.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:40:14.575+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:40:14.575+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:40:15.022+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:40:14.996+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:40:15.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:40:15.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.479 seconds
[2024-06-09T23:40:45.874+0000] {processor.py:161} INFO - Started process (PID=4605) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:40:45.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:40:45.878+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:40:45.878+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:40:46.274+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:40:46.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:40:46.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:40:46.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.425 seconds
[2024-06-09T23:41:17.370+0000] {processor.py:161} INFO - Started process (PID=4665) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:41:17.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:41:17.375+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:41:17.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:41:17.785+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:41:17.754+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:41:17.796+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:41:17.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.449 seconds
[2024-06-09T23:41:48.820+0000] {processor.py:161} INFO - Started process (PID=4725) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:41:48.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:41:48.824+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:41:48.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:41:49.264+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:41:49.237+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:41:49.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:41:49.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.471 seconds
[2024-06-09T23:42:20.180+0000] {processor.py:161} INFO - Started process (PID=4785) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:42:20.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:42:20.184+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:42:20.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:42:20.630+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:42:20.604+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:42:20.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:42:20.657+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.482 seconds
[2024-06-09T23:42:51.618+0000] {processor.py:161} INFO - Started process (PID=4845) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:42:51.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:42:51.621+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:42:51.621+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:42:52.077+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:42:52.049+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:42:52.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:42:52.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.490 seconds
[2024-06-09T23:43:23.064+0000] {processor.py:161} INFO - Started process (PID=4905) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:43:23.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:43:23.068+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:43:23.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:43:23.471+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:43:23.449+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:43:23.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:43:23.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.438 seconds
[2024-06-09T23:43:53.886+0000] {processor.py:161} INFO - Started process (PID=4965) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:43:53.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:43:53.891+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:43:53.891+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:43:54.341+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:43:54.320+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:43:54.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:43:54.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.483 seconds
[2024-06-09T23:44:25.193+0000] {processor.py:161} INFO - Started process (PID=5025) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:44:25.194+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:44:25.196+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:44:25.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:44:25.597+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:44:25.571+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:44:25.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:44:25.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.432 seconds
[2024-06-09T23:44:55.737+0000] {processor.py:161} INFO - Started process (PID=5085) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:44:55.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:44:55.743+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:44:55.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:44:56.209+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:44:56.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:44:56.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:44:56.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.498 seconds
[2024-06-09T23:45:26.997+0000] {processor.py:161} INFO - Started process (PID=5145) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:45:27.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:45:27.003+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:45:27.003+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:45:27.421+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:45:27.409+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:45:27.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:45:27.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.445 seconds
[2024-06-09T23:45:58.234+0000] {processor.py:161} INFO - Started process (PID=5205) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:45:58.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:45:58.239+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:45:58.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:45:58.682+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:45:58.667+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:45:58.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:45:58.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.471 seconds
[2024-06-09T23:46:29.580+0000] {processor.py:161} INFO - Started process (PID=5265) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:46:29.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:46:29.584+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:46:29.584+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:46:29.998+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:46:29.988+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:46:30.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:46:30.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.444 seconds
[2024-06-09T23:47:00.114+0000] {processor.py:161} INFO - Started process (PID=5326) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:47:00.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:47:00.118+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:47:00.118+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:47:00.531+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:47:00.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:47:00.538+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:47:00.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.445 seconds
[2024-06-09T23:47:31.206+0000] {processor.py:161} INFO - Started process (PID=5385) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:47:31.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:47:31.212+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:47:31.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:47:31.680+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:47:31.653+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:47:31.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:47:31.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.504 seconds
[2024-06-09T23:48:01.851+0000] {processor.py:161} INFO - Started process (PID=5448) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:48:01.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:48:01.855+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:48:01.854+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:48:02.300+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:48:02.289+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:48:02.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:48:02.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.475 seconds
[2024-06-09T23:48:32.890+0000] {processor.py:161} INFO - Started process (PID=5508) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:48:32.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:48:32.894+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:48:32.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:48:33.306+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:48:33.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:48:33.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:48:33.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.438 seconds
[2024-06-09T23:49:03.500+0000] {processor.py:161} INFO - Started process (PID=5571) to work on /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:49:03.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/news_realtime_pipeline.py for tasks to queue
[2024-06-09T23:49:03.504+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:49:03.504+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:49:04.027+0000] {logging_mixin.py:188} INFO - [2024-06-09T23:49:04.018+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/news_realtime_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_realtime_pipeline.py", line 17, in <module>
    from news_realtime import execute
  File "/opt/airflow/dags/news_realtime.py", line 2, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-06-09T23:49:04.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/news_realtime_pipeline.py
[2024-06-09T23:49:04.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/news_realtime_pipeline.py took 0.552 seconds
